name: Run Selenium Tests with Allure Report

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Print project tree
        run: tree .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Pull required browser image
        run: docker pull selenoid/vnc:chrome_114.0

      - name: Run tests with Docker Compose
        run: docker-compose up --build --abort-on-container-exit --exit-code-from test

      - name: Install Allure CLI
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure.zip -d allure-cli
          sudo mv allure-cli/allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report